services:
    app:
        build:
            context: .
            target: dev
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            NUXT_VALKEY_HOST: valkey
            NUXT_VALKEY_PORT: 6379
            NUXT_DATABASE_URL: postgres://squidy:secure_password@db/squid
            NUXT_MEILI_HOST: http://meilisearch:7700
            NUXT_MEILI_KEY: meili_cool_key
            NUXT_S3_ENDPOINT: http://seaweedfs:8333
            NUXT_S3_ACCESS_KEY: admin_access_key
            NUXT_S3_SECRET_KEY: admin_secret_key
        volumes:
            - .:/src
        depends_on:
            - valkey
            - db
            - seaweedfs

    valkey:
        image: valkey/valkey:latest
        ports:
            - '6379:6379'
        volumes:
            - valkey_data:/data

    db:
        image: postgres:18
        restart: unless-stopped
        environment:
            POSTGRES_USER: squidy
            POSTGRES_PASSWORD: secure_password
            POSTGRES_DB: squid
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql

    meilisearch:
        image: getmeili/meilisearch:latest
        restart: unless-stopped
        ports:
            - '7700:7700'
        environment:
            - MEILI_MASTER_KEY=meili_cool_key
            - MEILI_NO_ANALYTICS=true
        volumes:
            - meili_data:/meili_data

    seaweedfs:
        image: chrislusf/seaweedfs:latest
        restart: unless-stopped
        volumes:
            - ./s3.json:/etc/seaweedfs/s3.json:ro
            - seaweedfs_data:/data
        command: 'server -s3 -s3.config=/etc/seaweedfs/s3.json -dir=/data -ip.bind=0.0.0.0'

volumes:
    meili_data:
    valkey_data:
    seaweedfs_data:
    postgres_data:
